from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
from django.views.generic.base import TemplateView

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^$', 'budgie.views.home', name='home'),
    url(r'^index$', 'budgie.views.index', name='index'),
    url(r'^profile$', 'budgie.views.profile', name='profile'),
    url(r'^login$', 'budgie.views.user_login', name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^register$', 'budgie.views.register', name='register'),
     url(r'^confirm/(?P<email>[-.@_\w]+)/(?P<verification_id>[\w]+)', 'budgie.views.confirm', name='confirm'),
    #url(r'^activate', 'budgie.views.confirm', name='confirm'),
    url(r'^add_transaction$', 'budgie.views.add_transaction', name='add_transaction'),
    url(r'^view_transaction$', 'budgie.views.view_transaction', name='view_transaction'),
    url(r'^add_account$', 'budgie.views.add_account', name='add_account'),
    url(r'^dashboard/$', 'budgie.views.dashboard', name='dashboard'),
    url(r'^allaccounts/$', 'budgie.views.allaccounts', name='allaccounts'),
    url(r'^checkingaccounts/$', 'budgie.views.checkingaccounts', name='checkingaccounts'),
    url(r'^savingsaccounts/$', 'budgie.views.savingsaccounts', name='savingsaccounts'),
    url(r'^incvsexp/$', 'budgie.views.incvsexp', name='incvsexp'),
    url(r'^totalincome/$', 'budgie.views.totalincome', name='totalincome'),  
    url(r'^totalexpenses/$', 'budgie.views.totalexpenses', name='totalexpenses'),
    url(r'^budgetplan/$', 'budgie.views.budgetplan', name='budgetplan'),
    url(r'^budgetvsexpense/$', 'budgie.views.budgetvsexpense', name='budgetvsexpense'),
    url(r'^get_allaccounts$', 'budgie.views.get_allaccounts', name='get_allaccounts'),
    url(r'^get_checking_accounts$', 'budgie.views.get_checking_accounts', name='get_checking_accounts'), 
    url(r'^get_savings_accounts$', 'budgie.views.get_savings_accounts', name='get_savings_accounts'), 
    url(r'^get_incvsexp$', 'budgie.views.get_incvsexp', name='get_incvsexp'),  
    url(r'^get_totalincome$', 'budgie.views.get_totalincome', name='get_totalincome'),
    url(r'^get_totalexpenses$', 'budgie.views.get_totalexpenses', name='get_totalexpenses'),
    url(r'^get_budgetplan$', 'budgie.views.get_budgetplan', name='get_budgetplan'),
    url(r'^get_budgetvsexpense$', 'budgie.views.get_budgetvsexpense', name='get_budgetvsexpense'),
    url(r'^edit_account/(?P<id>\d+)$$', 'budgie.views.edit_account', name='edit_account'),  
    url(r'^create_assets$', 'budgie.views.create_assets', name='create_assets'),  
    url(r'^view_accounts$', 'budgie.views.view_accounts', name='view_accounts'),    
    url(r'^edit_assets/(?P<id>\d+)$$', 'budgie.views.edit_assets', name='edit_assets'),  
    url(r'^delete_assets/(?P<id>\d+)$$', 'budgie.views.delete_assets', name='delete_assets'),    
    url(r'^create_liability$', 'budgie.views.create_liability', name='create_liability'),   
    url(r'^edit_liability/(?P<id>\d+)$$', 'budgie.views.edit_liability', name='edit_liability'),  
    url(r'^delete_liability/(?P<id>\d+)$$', 'budgie.views.delete_liability', name='delete_liability'),    
    url(r'^create_budget$', 'budgie.views.create_budget', name='create_budget'),    
    url(r'^edit_budget/(?P<id>\d+)$$', 'budgie.views.edit_budget', name='edit_budget'),
    url(r'^delete_budget/(?P<id>\d+)$$', 'budgie.views.delete_budget', name='delete_budget'),
    url(r'^view_budget$', 'budgie.views.view_budget', name='view_budget'),     
    url(r'^create_goal$', 'budgie.views.create_goal', name='create_goal'), 
    url(r'^view_goals$', 'budgie.views.view_goals', name='view_goals'),    
    url(r'^edit_goal/(?P<id>\d+)$$', 'budgie.views.edit_goal', name='edit_goal'),     
    url(r'^delete_goal/(?P<id>\d+)$$', 'budgie.views.delete_goal', name='delete_goal'),     
    url(r'^get_accounts/(?P<account_type>[-\w]+)/$', 'budgie.views.get_accounts'), 
    url(r'^get_transactions/(?P<account_type>[-\w]+)/(?P<account_number>[-\w]+)/(?P<time_options>[-\w]+)/$', 'budgie.views.get_transactions'), 
    url(r'^about$', 'budgie.views.about', name='about'),
    url(r'^contact$', 'budgie.views.contact', name='contact'),
    url(r'^report_pdf$', 'budgie.views.report_pdf', name='report_pdf'),

)
